version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "uv"
    directory: "/jobs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/jobs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10